# Generated by Django 5.0.2 on 2024-02-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time_to_read',
            field=models.IntegerField(default=0, help_text='How much time does it take to read the post?(in min)'),
        ),
    ]
