# Generated by Django 5.0.2 on 2024-02-29 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=186)),
                ('phone', models.CharField(max_length=186)),
                ('email', models.CharField(max_length=320)),
                ('logo', models.ImageField(blank=True, upload_to='images')),
                ('author', models.CharField(max_length=186)),
                ('description', models.TextField()),
                ('keywords', models.CharField(help_text="You can seprate them with comma|','", max_length=600)),
                ('founder_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=186)),
                ('description', models.TextField()),
            ],
        ),
    ]
