# Generated by Django 5.0.2 on 2024-02-20 10:09

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.IntegerField(choices=[(1, 'About'), (2, 'Services')], default=1, unique=True)),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
        migrations.AddField(
            model_name='config',
            name='logo',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
