# Generated by Django 5.0.2 on 2024-02-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_page_config_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='author',
            field=models.CharField(default='Moe Mirfallahi', max_length=186),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='description',
            field=models.TextField(default='Hi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='config',
            name='keywords',
            field=models.CharField(default='The best company, construction are', help_text="You can seprate them with comma|','", max_length=600),
            preserve_default=False,
        ),
    ]
