# Generated by Django 5.0.2 on 2024-02-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_config_author_config_description_config_keywords'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page',
        ),
        migrations.AddField(
            model_name='config',
            name='founder_image',
            field=models.ImageField(default='media\\images\\somewhere.jpg', upload_to='images/'),
            preserve_default=False,
        ),
    ]
