# Generated by Django 5.0.2 on 2024-02-26 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_page_config_founder_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimonial',
            new_name='Remark',
        ),
    ]
